# アプリのログインパスワード
APP_PASSWORD = "admin"

# ▼ ここに追記してください
GEMINI_API_KEY = "AIzaSyAPSjbPoxz_pLqEX1ByYLZQh0IlKUOzG7w"

[supabase]
url = "https://bghrnsnyvjrpxirlqhrn.supabase.co"
key = "sb_secret_DgNwmTAriFJVzG-iw1XPvA_FLRIkDei"